node {
    //URL to Github repository https://github.com/<owner>/<repo>
    def GITHUB_REPO_URL="https://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@github.com/rslangehennig/Online-Botanicals"
    //Retrieve ENV ID values for DEV and QA from "Download attributes from API" json file
    def VELOCITY_ENV_ID_DEV="a4a91beb-e2be-4da5-896a-78632d3b451c"
    //VELOCITY_APP_NAME must match your Velocity pipeline application name
    def VELOCITY_APP_NAME="Online-Botanicals"
    //Version number 
    def VERSION_NUMBER="2.0"
    //Do not change below this line.
    def GIT_COMMIT
    
    stage ('cloning the repository'){
        currentBuild.displayName = "${VERSION_NUMBER}.${BUILD_NUMBER}"
        echo currentBuild.displayName = "${currentBuild.displayName}"
        majorVersion="${BUILD_NUMBER}"
        def scm = git branch: 'main', url: "${GITHUB_REPO_URL}"
        GIT_COMMIT = sh(returnStdout: true, script: "git rev-parse HEAD").trim()
        echo "GIT_COMMIT=${GIT_COMMIT}"
    }
    
    stage ('build') {
        sh '''echo $WORKSPACE
        pwd
        ls -al
        source '/downloads/ace-developer/ace-12.0.7.0/server/bin/mqsiprofile'
        #ibmint package --input-path . --output-bar aceivt.bar --project JGRACEIVT
        ibmint package --input-path . --output-bar jgr-cp4i-aceivbar'''
    }
    
    stage ('Push Artifact of Build to UCD') {
         sh '''export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-1.el7_9.x86_64/jre
               export UCD_AUTH_TOKEN="4fdac9bf-4c18-4726-b675-2f3ab85c4882"
               export UCD_WEB_URL="https://52.117.32.21:8444"
               
               echo $BUILD_NUMBER
               CURRENT_BUILD="2.0.${BUILD_NUMBER}"
               # Create new component version
               echo "Create new component version"
               udclient/udclient -weburl $UCD_WEB_URL -authtoken $UCD_AUTH_TOKEN createVersion -component Online-Botanical-APP -name $CURRENT_BUILD
               udclient/udclient -weburl $UCD_WEB_URL -authtoken $UCD_AUTH_TOKEN addVersionLink -component Online-Botanical-APP -version $CURRENT_BUILD -linkName "Jenkins Pipeline" -link http://67.228.223.183:8080/job/Online%20Botanical/job/Online-Botanical-Build-Pipeline/${BUILD_NUMBER}/
               udclient/udclient -weburl $UCD_WEB_URL -authtoken $UCD_AUTH_TOKEN addVersionFiles -component Online-Botanical-APP -version $CURRENT_BUILD -base "/root/.jenkins/workspace/Online Botanical/Online-Botanical-Build-Pipeline/output2"
               # Add a component status to allow it to pass gates in UCD
               #echo "Adding component status"
               #udclient/udclient -weburl $UCD_WEB_URL -authtoken $UCD_AUTH_TOKEN addVersionStatus -component Online-Botanical-APP -version $CURRENT_BUILD -status "Unit Tests Passed"
       
               # Create snapshot
               #echo "Create new snapshot"
               #cp urbancode/snapshot.json .
               #sed -i "s/MYNAME/$CURRENT_BUILD/g" snapshot.json
               #cat snapshot.json
               #udclient/udclient -weburl $UCD_WEB_URL -authtoken $UCD_AUTH_TOKEN createSnapshot snapshot.json
               '''
    }
}
